import {
  BoardFieldsEntity,
  FieldType,
  CurrencyType,
} from './board.fields.entity';
import { UsersEntity } from './users.entity';

export const fieldsForSave: BoardFieldsEntity[] = [
  {
    fieldPosition: 0,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/start.png',
    name: 'start',
    fieldCorner: 0,
    level: 0,
    type: FieldType.START,
  },
  {
    fieldPosition: 1,
    price: 600,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/1_perfumery/chanel.svg',
    fieldGroup: 1,
    fieldLine: 0,
    name: 'chanel',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 2,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/tax_income.png',
    fieldLine: 0,
    name: 'tax_income',
    mnplSpecial: 1,
    level: 0,
    price: 2000,
    type: FieldType.TAX,
  },

  {
    fieldPosition: 3,
    price: 600,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/1_perfumery/hugo_boss.svg',
    fieldGroup: 1,
    fieldLine: 0,
    name: 'hugo_boss',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 4,
    price: 800,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/1_perfumery/hugo_boss.svg',
    fieldGroup: 1,
    fieldLine: 0,
    name: 'iv_roche',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 5,
    price: 2000,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/mercedes.svg',
    fieldGroup: 0,
    fieldLine: 0,
    name: 'mercedes',
    level: 0,
    type: FieldType.AUTO,
  },
  {
    fieldPosition: 6,
    price: 1000,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/2_clothing/adidas.svg',
    fieldGroup: 2,
    fieldLine: 0,
    name: 'adidas',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 7,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance.png',
    fieldLine: 0,
    name: 'chance',
    mnplSpecial: 1,
    level: 0,
    type: FieldType.CHANCE,
  },
  {
    fieldPosition: 8,
    price: 1000,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/2_clothing/puma.svg',
    fieldGroup: 2,
    fieldLine: 0,
    name: 'puma',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 9,
    price: 1200,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/2_clothing/lacoste.svg',
    fieldGroup: 2,
    fieldLine: 0,
    name: 'lacoste',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 10,
    fieldCorner: 1,
    imgSrc: '',
    isJail: true,
    name: 'jail',
    level: 0,
    type: FieldType.TAKE_REST,
  },
  {
    fieldPosition: 11,
    price: 1400,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/3_web/vk.svg',
    fieldGroup: 3,
    fieldLine: 1,
    name: 'vk',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 12,
    price: 1500,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/9_games/rockstar_games.svg',
    fieldGroup: 9,
    fieldLine: 1,
    name: 'rockstar_games',
    level: 0,
    type: FieldType.IT,
    currency: CurrencyType.MULTIPLIER,
  },
  {
    fieldPosition: 13,
    price: 1400,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/3_web/facebook.svg',
    fieldGroup: 3,
    fieldLine: 1,
    name: 'facebook',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 14,
    price: 1600,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/3_web/twitter.svg',
    fieldGroup: 3,
    fieldLine: 1,
    name: 'twitter',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 15,
    price: 2000,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/audi.svg',
    fieldGroup: 0,
    fieldLine: 1,
    name: 'audi',
    level: 0,
    type: FieldType.AUTO,
  },
  {
    fieldPosition: 16,
    price: 1800,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/4_drinks/coca_cola.svg',
    fieldGroup: 4,
    fieldLine: 1,
    name: 'coca_cola',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 17,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance.png',
    fieldLine: 1,
    name: 'chance',
    mnplSpecial: 1,
    level: 0,
    type: FieldType.CHANCE,
  },
  {
    fieldPosition: 18,
    price: 1800,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/4_drinks/pepsi.svg',
    fieldGroup: 4,
    fieldLine: 1,
    name: 'pepsi',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 19,
    price: 2000,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/4_drinks/fanta.svg',
    fieldGroup: 4,
    fieldLine: 1,
    name: 'fanta',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 20,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/jackpot.svg',
    fieldCorner: 2,
    mnplSpecial: 1,
    name: 'casino',
    level: 0,
    type: FieldType.CASINO,
  },
  {
    fieldPosition: 21,
    price: 2200,
    imgSrc:
      'https://m1.dogecdn.wtf/fields/brands/5_airlines/american_airlines.svg',
    fieldLine: 2,
    fieldGroup: 5,
    name: 'american_airlines',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 22,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance.png',
    mnplSpecial: 1,
    fieldLine: 2,
    name: 'chance',
    level: 0,
    type: FieldType.CHANCE,
  },
  {
    fieldPosition: 23,
    price: 2200,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/5_airlines/lufthansa.svg',
    fieldGroup: 5,
    fieldLine: 2,
    name: 'lufthansa',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 24,
    price: 2400,
    imgSrc:
      'https://m1.dogecdn.wtf/fields/brands/5_airlines/british_airways.svg',
    fieldGroup: 5,
    fieldLine: 2,
    name: 'british_airways',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 25,
    price: 2000,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/ford.svg',
    fieldGroup: 0,
    fieldLine: 2,
    name: 'ford',
    level: 0,
    type: FieldType.AUTO,
  },
  {
    fieldPosition: 26,
    price: 2600,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/6_food/mcdonalds.svg',
    fieldGroup: 6,
    fieldLine: 2,
    name: 'mcdonalds',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 27,
    price: 2600,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/6_food/burger_king.svg',
    fieldGroup: 6,
    fieldLine: 2,
    name: 'burger_king',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 28,
    price: 1500,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/9_games/rovio.svg',
    fieldGroup: 9,
    fieldLine: 2,
    name: 'rovio',
    level: 0,
    type: FieldType.IT,
    currency: CurrencyType.MULTIPLIER,
  },
  {
    fieldPosition: 29,
    price: 2800,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/6_food/kfc.svg',
    fieldGroup: 6,
    fieldLine: 2,
    name: 'kfc',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 30,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/goToJail.png',
    mnplSpecial: 1,
    fieldCorner: 3,
    name: 'arest',
    level: 0,
    type: FieldType.JAIL,
  },
  {
    fieldPosition: 31,
    price: 3000,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/7_hotels/holiday_inn.svg',
    fieldGroup: 7,
    fieldLine: 3,
    name: 'holiday_inn',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 32,
    price: 3000,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/7_hotels/radisson_blu.svg',
    fieldGroup: 7,
    fieldLine: 3,
    name: 'radisson_blu',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 33,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance_rotated.png',
    mnplSpecial: 1,
    fieldLine: 3,
    name: 'chance_rotated',
    level: 0,
    type: FieldType.CHANCE,
  },
  {
    fieldPosition: 34,
    price: 3200,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/7_hotels/novotel.svg',
    fieldGroup: 7,
    fieldLine: 3,
    name: 'novotel',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 35,
    price: 2000,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/land_rover.svg',
    fieldGroup: 0,
    fieldLine: 3,
    name: 'land_rover',
    level: 0,
    type: FieldType.AUTO,
  },
  {
    fieldPosition: 36,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/tax_luxury.png',
    mnplSpecial: 1,
    fieldLine: 3,
    name: 'tax_luxury',
    level: 0,
    price: 1000,
    type: FieldType.TAX,
  },
  {
    fieldPosition: 37,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/8_smartphones/apple.svg',
    fieldLine: 3,
    fieldGroup: 8,
    price: 3500,
    name: 'apple',
    level: 0,
    type: FieldType.COMPANY,
  },
  {
    fieldPosition: 38,
    imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance_rotated.png',
    mnplSpecial: 1,
    fieldLine: 3,
    name: 'chance_rotated',
    level: 0,
    type: FieldType.CHANCE,
  },
  {
    fieldPosition: 39,
    imgSrc: 'https://m1.dogecdn.wtf/fields/brands/8_smartphones/nokia.svg',
    fieldLine: 3,
    fieldGroup: 8,
    price: 4000,
    name: 'nokia',
    level: 0,
    type: FieldType.COMPANY,
  },
];

export const users: UsersEntity[] = [
  {
    name: 'Konstantin',
    registrationType: 'vk',
    vip: true,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Diman',
    registrationType: 'vk',
    vip: false,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Feodr',
    registrationType: 'vk',
    vip: false,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Ivan',
    registrationType: 'vk',
    vip: false,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Maxim',
    registrationType: 'vk',
    vip: true,
    avatar: '/avatars/konstanstin.png',
  },
];
