import {
  BoardFieldsEntity,
  FieldType,
  CurrencyType,
} from './board.fields.entity';
import { UsersEntity } from './users.entity';

// const calcRent = (price: number, stars: number) =>
//   Math.floor((price / 1000) * stars) * 10;

export const fieldsForSave = (): BoardFieldsEntity[] => {
  return [
    {
      fieldPosition: 0,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/start.png',
      name: 'start',
      fieldCorner: 0,
      level: 0,
      type: FieldType.START,
    },
    {
      fieldPosition: 1,
      rent: {
        baseRent: 20,
        bigStar: 100,
        fourStar: 300,
        freeStar: 900,
        twoStar: 1600,
        oneStar: 2500,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 0,
        pledgePrice: 0,
        buyoutPrice: 0,
        branchPrice: 0,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/1_perfumery/chanel.svg',
      fieldGroup: 1,
      fieldLine: 0,
      name: 'chanel',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 2,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/tax_income.png',
      fieldLine: 0,
      name: 'tax_income',
      mnplSpecial: 1,
      level: 0,
      rent: {
        baseRent: 1,
        bigStar: 1,
        fourStar: 1,
        freeStar: 1,
        twoStar: 1,
        oneStar: 1,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 1,
        pledgePrice: 1,
        buyoutPrice: 1,
        branchPrice: 1,
      },
      type: FieldType.TAX,
    },

    {
      fieldPosition: 3,
      rent: {
        baseRent: 2,
        bigStar: 2,
        fourStar: 2,
        freeStar: 2,
        twoStar: 2,
        oneStar: 2,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 2,
        pledgePrice: 2,
        buyoutPrice: 2,
        branchPrice: 2,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/1_perfumery/hugo_boss.svg',
      fieldGroup: 1,
      fieldLine: 0,
      name: 'hugo_boss',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 4,
      rent: {
        baseRent: 3,
        bigStar: 3,
        fourStar: 3,
        freeStar: 3,
        twoStar: 3,
        oneStar: 3,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 3,
        pledgePrice: 3,
        buyoutPrice: 3,
        branchPrice: 3,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/1_perfumery/hugo_boss.svg',
      fieldGroup: 1,
      fieldLine: 0,
      name: 'iv_roche',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 5,
      rent: {
        baseRent: 250,
        bigStar: 0,
        fourStar: 2000,
        freeStar: 200,
        twoStar: 500,
        oneStar: 1000,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 0,
        pledgePrice: 0,
        buyoutPrice: 0,
        branchPrice: 2000,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/mercedes.svg',
      fieldGroup: 0,
      fieldLine: 0,
      name: 'mercedes',
      level: 0,
      type: FieldType.AUTO,
    },
    {
      fieldPosition: 6,
      rent: {
        baseRent: 5,
        bigStar: 5,
        fourStar: 5,
        freeStar: 5,
        twoStar: 5,
        oneStar: 5,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 5,
        pledgePrice: 5,
        buyoutPrice: 5,
        branchPrice: 5,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/2_clothing/adidas.svg',
      fieldGroup: 2,
      fieldLine: 0,
      name: 'adidas',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 7,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance.png',
      fieldLine: 0,
      name: 'chance',
      mnplSpecial: 1,
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 8,
      rent: {
        baseRent: 6,
        bigStar: 6,
        fourStar: 6,
        freeStar: 6,
        twoStar: 6,
        oneStar: 6,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 6,
        pledgePrice: 6,
        buyoutPrice: 6,
        branchPrice: 6,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/2_clothing/puma.svg',
      fieldGroup: 2,
      fieldLine: 0,
      name: 'puma',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 9,
      rent: {
        baseRent: 7,
        bigStar: 7,
        fourStar: 7,
        freeStar: 7,
        twoStar: 7,
        oneStar: 7,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 7,
        pledgePrice: 7,
        buyoutPrice: 7,
        branchPrice: 7,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/2_clothing/lacoste.svg',
      fieldGroup: 2,
      fieldLine: 0,
      name: 'lacoste',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 10,
      fieldCorner: 1,
      imgSrc: '',
      isJail: true,
      name: 'jail',
      level: 0,
      type: FieldType.TAKE_REST,
    },
    {
      fieldPosition: 11,
      rent: {
        baseRent: 8,
        bigStar: 8,
        fourStar: 8,
        freeStar: 8,
        twoStar: 8,
        oneStar: 8,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 8,
        pledgePrice: 8,
        buyoutPrice: 8,
        branchPrice: 9,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/3_web/vk.svg',
      fieldGroup: 3,
      fieldLine: 1,
      name: 'vk',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 12,
      rent: {
        baseRent: 9,
        bigStar: 9,
        fourStar: 9,
        freeStar: 9,
        twoStar: 9,
        oneStar: 9,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 9,
        pledgePrice: 9,
        buyoutPrice: 9,
        branchPrice: 9,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/9_games/rockstar_games.svg',
      fieldGroup: 9,
      fieldLine: 1,
      name: 'rockstar_games',
      level: 0,
      type: FieldType.IT,
      currency: CurrencyType.MULTIPLIER,
    },
    {
      fieldPosition: 13,
      rent: {
        baseRent: 10,
        paymentMultiplier: 0,
        bigStar: 10,
        fourStar: 10,
        freeStar: 10,
        twoStar: 10,
        oneStar: 10,
      },
      price: {
        startPrice: 10,
        pledgePrice: 10,
        buyoutPrice: 10,
        branchPrice: 10,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/3_web/facebook.svg',
      fieldGroup: 3,
      fieldLine: 1,
      name: 'facebook',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 14,
      rent: {
        baseRent: 11,
        bigStar: 11,
        fourStar: 11,
        freeStar: 11,
        twoStar: 11,
        oneStar: 11,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 11,
        pledgePrice: 11,
        buyoutPrice: 11,
        branchPrice: 11,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/3_web/twitter.svg',
      fieldGroup: 3,
      fieldLine: 1,
      name: 'twitter',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 15,
      rent: {
        baseRent: 250,
        bigStar: 0,
        fourStar: 2000,
        freeStar: 200,
        twoStar: 500,
        oneStar: 1000,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 0,
        pledgePrice: 0,
        buyoutPrice: 0,
        branchPrice: 2000,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/audi.svg',
      fieldGroup: 0,
      fieldLine: 1,
      name: 'audi',
      level: 0,
      type: FieldType.AUTO,
    },
    {
      fieldPosition: 16,
      rent: {
        baseRent: 13,
        bigStar: 13,
        fourStar: 13,
        freeStar: 13,
        twoStar: 13,
        oneStar: 13,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 13,
        pledgePrice: 13,
        buyoutPrice: 13,
        branchPrice: 13,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/4_drinks/coca_cola.svg',
      fieldGroup: 4,
      fieldLine: 1,
      name: 'coca_cola',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 17,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance.png',
      fieldLine: 1,
      name: 'chance',
      mnplSpecial: 1,
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 18,
      rent: {
        baseRent: 14,
        bigStar: 14,
        fourStar: 14,
        freeStar: 14,
        twoStar: 14,
        oneStar: 14,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 14,
        pledgePrice: 14,
        buyoutPrice: 14,
        branchPrice: 14,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/4_drinks/pepsi.svg',
      fieldGroup: 4,
      fieldLine: 1,
      name: 'pepsi',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 19,
      rent: {
        baseRent: 15,
        bigStar: 15,
        fourStar: 15,
        freeStar: 15,
        twoStar: 15,
        oneStar: 15,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 15,
        pledgePrice: 15,
        buyoutPrice: 15,
        branchPrice: 15,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/4_drinks/fanta.svg',
      fieldGroup: 4,
      fieldLine: 1,
      name: 'fanta',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 20,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/jackpot.svg',
      fieldCorner: 2,
      mnplSpecial: 1,
      name: 'casino',
      level: 0,
      type: FieldType.CASINO,
    },
    {
      fieldPosition: 21,
      rent: {
        baseRent: 16,
        bigStar: 16,
        fourStar: 16,
        freeStar: 16,
        twoStar: 16,
        oneStar: 16,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 16,
        pledgePrice: 16,
        buyoutPrice: 16,
        branchPrice: 16,
      },
      imgSrc:
        'https://m1.dogecdn.wtf/fields/brands/5_airlines/american_airlines.svg',
      fieldLine: 2,
      fieldGroup: 5,
      name: 'american_airlines',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 22,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance.png',
      mnplSpecial: 1,
      fieldLine: 2,
      name: 'chance',
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 23,
      rent: {
        baseRent: 17,
        bigStar: 17,
        fourStar: 17,
        freeStar: 17,
        twoStar: 17,
        oneStar: 17,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 17,
        pledgePrice: 17,
        buyoutPrice: 17,
        branchPrice: 17,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/5_airlines/lufthansa.svg',
      fieldGroup: 5,
      fieldLine: 2,
      name: 'lufthansa',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 24,
      rent: {
        baseRent: 18,
        bigStar: 18,
        fourStar: 18,
        freeStar: 18,
        twoStar: 18,
        oneStar: 18,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 18,
        pledgePrice: 18,
        buyoutPrice: 18,
        branchPrice: 18,
      },
      imgSrc:
        'https://m1.dogecdn.wtf/fields/brands/5_airlines/british_airways.svg',
      fieldGroup: 5,
      fieldLine: 2,
      name: 'british_airways',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 25,
      rent: {
        baseRent: 250,
        bigStar: 0,
        fourStar: 2000,
        freeStar: 200,
        twoStar: 500,
        oneStar: 1000,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 0,
        pledgePrice: 0,
        buyoutPrice: 0,
        branchPrice: 2000,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/ford.svg',
      fieldGroup: 0,
      fieldLine: 2,
      name: 'ford',
      level: 0,
      type: FieldType.AUTO,
    },
    {
      fieldPosition: 26,
      rent: {
        baseRent: 20,
        bigStar: 20,
        fourStar: 20,
        freeStar: 20,
        twoStar: 20,
        oneStar: 20,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 20,
        pledgePrice: 20,
        buyoutPrice: 20,
        branchPrice: 20,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/6_food/mcdonalds.svg',
      fieldGroup: 6,
      fieldLine: 2,
      name: 'mcdonalds',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 27,
      rent: {
        baseRent: 21,
        bigStar: 21,
        fourStar: 21,
        freeStar: 21,
        twoStar: 21,
        oneStar: 21,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 21,
        pledgePrice: 21,
        buyoutPrice: 21,
        branchPrice: 21,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/6_food/burger_king.svg',
      fieldGroup: 6,
      fieldLine: 2,
      name: 'burger_king',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 28,
      rent: {
        baseRent: 22,
        bigStar: 22,
        fourStar: 22,
        freeStar: 22,
        twoStar: 22,
        oneStar: 22,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 22,
        pledgePrice: 22,
        buyoutPrice: 22,
        branchPrice: 22,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/9_games/rovio.svg',
      fieldGroup: 9,
      fieldLine: 2,
      name: 'rovio',
      level: 0,
      type: FieldType.IT,
      currency: CurrencyType.MULTIPLIER,
    },
    {
      fieldPosition: 29,
      rent: {
        baseRent: 23,
        bigStar: 23,
        fourStar: 23,
        freeStar: 23,
        twoStar: 23,
        oneStar: 23,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 23,
        pledgePrice: 23,
        buyoutPrice: 23,
        branchPrice: 23,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/6_food/kfc.svg',
      fieldGroup: 6,
      fieldLine: 2,
      name: 'kfc',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 30,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/goToJail.png',
      mnplSpecial: 1,
      fieldCorner: 3,
      name: 'arest',
      level: 0,
      type: FieldType.JAIL,
    },
    {
      fieldPosition: 31,
      rent: {
        baseRent: 24,
        bigStar: 24,
        fourStar: 24,
        freeStar: 24,
        twoStar: 24,
        oneStar: 24,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 24,
        pledgePrice: 24,
        buyoutPrice: 24,
        branchPrice: 24,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/7_hotels/holiday_inn.svg',
      fieldGroup: 7,
      fieldLine: 3,
      name: 'holiday_inn',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 32,
      rent: {
        baseRent: 25,
        bigStar: 25,
        fourStar: 25,
        freeStar: 25,
        twoStar: 25,
        oneStar: 25,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 25,
        pledgePrice: 25,
        buyoutPrice: 25,
        branchPrice: 25,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/7_hotels/radisson_blu.svg',
      fieldGroup: 7,
      fieldLine: 3,
      name: 'radisson_blu',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 33,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance_rotated.png',
      mnplSpecial: 1,
      fieldLine: 3,
      name: 'chance_rotated',
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 34,
      rent: {
        baseRent: 26,
        bigStar: 26,
        fourStar: 26,
        freeStar: 26,
        twoStar: 26,
        oneStar: 26,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 26,
        pledgePrice: 26,
        buyoutPrice: 26,
        branchPrice: 26,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/7_hotels/novotel.svg',
      fieldGroup: 7,
      fieldLine: 3,
      name: 'novotel',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 35,
      rent: {
        baseRent: 250,
        bigStar: 0,
        fourStar: 2000,
        freeStar: 200,
        twoStar: 500,
        oneStar: 1000,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 0,
        pledgePrice: 0,
        buyoutPrice: 0,
        branchPrice: 2000,
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/land_rover.svg',
      fieldGroup: 0,
      fieldLine: 3,
      name: 'land_rover',
      level: 0,
      type: FieldType.AUTO,
    },
    {
      fieldPosition: 36,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/tax_luxury.png',
      mnplSpecial: 1,
      fieldLine: 3,
      name: 'tax_luxury',
      level: 0,
      rent: {
        baseRent: 28,
        bigStar: 28,
        fourStar: 28,
        freeStar: 28,
        twoStar: 28,
        oneStar: 28,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 28,
        pledgePrice: 28,
        buyoutPrice: 28,
        branchPrice: 28,
      },
      type: FieldType.TAX,
    },
    {
      fieldPosition: 37,
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/8_smartphones/apple.svg',
      fieldLine: 3,
      fieldGroup: 8,
      rent: {
        baseRent: 3500,
        bigStar: 15000,
        fourStar: 13000,
        freeStar: 11000,
        twoStar: 1750,
        oneStar: 5000,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 2000,
        pledgePrice: 2100,
        buyoutPrice: 1750,
        branchPrice: 3500,
      },
      name: 'apple',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 38,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance_rotated.png',
      mnplSpecial: 1,
      fieldLine: 3,
      name: 'chance_rotated',
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 39,
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/8_smartphones/nokia.svg',
      fieldLine: 3,
      fieldGroup: 8,
      rent: {
        baseRent: 500,
        bigStar: 20000,
        fourStar: 17000,
        freeStar: 14000,
        twoStar: 2000,
        oneStar: 6000,
        paymentMultiplier: 0,
      },
      price: {
        startPrice: 2000,
        pledgePrice: 2400,
        buyoutPrice: 2000,
        branchPrice: 4000,
      },
      name: 'nokia',
      level: 0,
      type: FieldType.COMPANY,
    },
  ];
};

export const users: UsersEntity[] = [
  {
    name: 'Konstantin',
    registrationType: 'vk',
    vip: true,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Diman',
    registrationType: 'vk',
    vip: false,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Feodr',
    registrationType: 'vk',
    vip: false,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Ivan',
    registrationType: 'vk',
    vip: false,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Maxim',
    registrationType: 'vk',
    vip: true,
    avatar: '/avatars/konstanstin.png',
  },
];

console.log(1231231231, fieldsForSave());
