import {
  BoardFieldsEntity,
  FieldType,
  CurrencyType,
} from './board.fields.entity';
import { UsersEntity } from './users.entity';

const calcBought = (price: number) => Math.floor((price / 1000) * 12.5) * 10;

const calcBuyout = (price: number) => Math.floor((price / 1000) * 1) * 10;

const calcBranch = (price: number) => Math.floor((price / 1000) * 1) * 10;

const calcPledge = (price: number) => Math.floor((price / 1000) * 1) * 10;

const calcRent = (price: number, stars: number) =>
  Math.floor((price / 1000) * stars) * 10;

const prAr = [
  600,
  2000,
  600,
  600,
  2000,
  1000,
  1000,
  1200,
  1400,
  1500,
  1400,
  1600,
  2000,
  1800,
  1800,
  2000,
  2200,
  2200,
  2400,
  2000,
  2600,
  2600,
  1500,
  2800,
  3000,
  3000,
  3200,
  2000,
  1000,
  3500,
  4000,
];
export const fieldsForSave = (): BoardFieldsEntity[] => {
  return [
    {
      fieldPosition: 0,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/start.png',
      name: 'start',
      fieldCorner: 0,
      level: 0,
      type: FieldType.START,
    },
    {
      fieldPosition: 1,
      rent: {
        baseRent: calcBought(prAr[0]),
        bigStar: calcRent(prAr[0], 5),
        fourStar: calcRent(prAr[0], 4),
        freeStar: calcRent(prAr[0], 3),
        oneStar: calcRent(prAr[0], 1),
        twoStar: calcRent(prAr[0], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[0]),
        buyoutPrice: calcBuyout(prAr[0]),
        pledgePrice: calcPledge(prAr[0]),
        startPrice: prAr[0],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/1_perfumery/chanel.svg',
      fieldGroup: 1,
      fieldLine: 0,
      name: 'chanel',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 2,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/tax_income.png',
      fieldLine: 0,
      name: 'tax_income',
      mnplSpecial: 1,
      level: 0,
      rent: {
        baseRent: calcBought(prAr[1]),
        bigStar: calcRent(prAr[1], 5),
        fourStar: calcRent(prAr[1], 4),
        freeStar: calcRent(prAr[1], 3),
        oneStar: calcRent(prAr[1], 1),
        twoStar: calcRent(prAr[1], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[1]),
        buyoutPrice: calcBuyout(prAr[1]),
        pledgePrice: calcPledge(prAr[1]),
        startPrice: prAr[1],
      },
      type: FieldType.TAX,
    },

    {
      fieldPosition: 3,
      rent: {
        baseRent: calcBought(prAr[2]),
        bigStar: calcRent(prAr[2], 5),
        fourStar: calcRent(prAr[2], 4),
        freeStar: calcRent(prAr[2], 3),
        oneStar: calcRent(prAr[2], 1),
        twoStar: calcRent(prAr[2], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[2]),
        buyoutPrice: calcBuyout(prAr[2]),
        pledgePrice: calcPledge(prAr[2]),
        startPrice: prAr[2],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/1_perfumery/hugo_boss.svg',
      fieldGroup: 1,
      fieldLine: 0,
      name: 'hugo_boss',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 4,
      rent: {
        baseRent: calcBought(prAr[3]),
        bigStar: calcRent(prAr[3], 5),
        fourStar: calcRent(prAr[3], 4),
        freeStar: calcRent(prAr[3], 3),
        oneStar: calcRent(prAr[3], 1),
        twoStar: calcRent(prAr[3], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[3]),
        buyoutPrice: calcBuyout(prAr[3]),
        pledgePrice: calcPledge(prAr[3]),
        startPrice: prAr[3],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/1_perfumery/hugo_boss.svg',
      fieldGroup: 1,
      fieldLine: 0,
      name: 'iv_roche',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 5,
      rent: {
        baseRent: calcBought(prAr[4]),
        bigStar: calcRent(prAr[4], 5),
        fourStar: calcRent(prAr[4], 4),
        freeStar: calcRent(prAr[4], 3),
        oneStar: calcRent(prAr[4], 1),
        twoStar: calcRent(prAr[4], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[4]),
        buyoutPrice: calcBuyout(prAr[4]),
        pledgePrice: calcPledge(prAr[4]),
        startPrice: prAr[4],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/mercedes.svg',
      fieldGroup: 0,
      fieldLine: 0,
      name: 'mercedes',
      level: 0,
      type: FieldType.AUTO,
    },
    {
      fieldPosition: 6,
      rent: {
        baseRent: calcBought(prAr[5]),
        bigStar: calcRent(prAr[5], 5),
        fourStar: calcRent(prAr[5], 4),
        freeStar: calcRent(prAr[5], 3),
        oneStar: calcRent(prAr[5], 1),
        twoStar: calcRent(prAr[5], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[5]),
        buyoutPrice: calcBuyout(prAr[5]),
        pledgePrice: calcPledge(prAr[5]),
        startPrice: prAr[5],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/2_clothing/adidas.svg',
      fieldGroup: 2,
      fieldLine: 0,
      name: 'adidas',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 7,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance.png',
      fieldLine: 0,
      name: 'chance',
      mnplSpecial: 1,
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 8,
      rent: {
        baseRent: calcBought(prAr[6]),
        bigStar: calcRent(prAr[6], 5),
        fourStar: calcRent(prAr[6], 4),
        freeStar: calcRent(prAr[6], 3),
        oneStar: calcRent(prAr[6], 1),
        twoStar: calcRent(prAr[6], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[6]),
        buyoutPrice: calcBuyout(prAr[6]),
        pledgePrice: calcPledge(prAr[6]),
        startPrice: prAr[6],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/2_clothing/puma.svg',
      fieldGroup: 2,
      fieldLine: 0,
      name: 'puma',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 9,
      rent: {
        baseRent: calcBought(prAr[7]),
        bigStar: calcRent(prAr[7], 5),
        fourStar: calcRent(prAr[7], 4),
        freeStar: calcRent(prAr[7], 3),
        oneStar: calcRent(prAr[7], 1),
        twoStar: calcRent(prAr[7], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[7]),
        buyoutPrice: calcBuyout(prAr[7]),
        pledgePrice: calcPledge(prAr[7]),
        startPrice: prAr[7],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/2_clothing/lacoste.svg',
      fieldGroup: 2,
      fieldLine: 0,
      name: 'lacoste',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 10,
      fieldCorner: 1,
      imgSrc: '',
      isJail: true,
      name: 'jail',
      level: 0,
      type: FieldType.TAKE_REST,
    },
    {
      fieldPosition: 11,
      rent: {
        baseRent: calcBought(prAr[8]),
        bigStar: calcRent(prAr[8], 5),
        fourStar: calcRent(prAr[8], 4),
        freeStar: calcRent(prAr[8], 3),
        oneStar: calcRent(prAr[8], 1),
        twoStar: calcRent(prAr[8], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[8]),
        buyoutPrice: calcBuyout(prAr[8]),
        pledgePrice: calcPledge(prAr[8]),
        startPrice: prAr[9],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/3_web/vk.svg',
      fieldGroup: 3,
      fieldLine: 1,
      name: 'vk',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 12,
      rent: {
        baseRent: calcBought(prAr[9]),
        bigStar: calcRent(prAr[9], 5),
        fourStar: calcRent(prAr[9], 4),
        freeStar: calcRent(prAr[9], 3),
        oneStar: calcRent(prAr[9], 1),
        twoStar: calcRent(prAr[9], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[9]),
        buyoutPrice: calcBuyout(prAr[9]),
        pledgePrice: calcPledge(prAr[9]),
        startPrice: prAr[9],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/9_games/rockstar_games.svg',
      fieldGroup: 9,
      fieldLine: 1,
      name: 'rockstar_games',
      level: 0,
      type: FieldType.IT,
      currency: CurrencyType.MULTIPLIER,
    },
    {
      fieldPosition: 13,
      rent: {
        baseRent: calcBought(prAr[10]),
        paymentMultiplier: 0,
        bigStar: calcRent(prAr[10], 5),
        fourStar: calcRent(prAr[10], 4),
        freeStar: calcRent(prAr[10], 3),
        oneStar: calcRent(prAr[10], 1),
        twoStar: calcRent(prAr[10], 2),
      },
      price: {
        branchPrice: calcBranch(prAr[10]),
        buyoutPrice: calcBuyout(prAr[10]),
        pledgePrice: calcPledge(prAr[10]),
        startPrice: prAr[10],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/3_web/facebook.svg',
      fieldGroup: 3,
      fieldLine: 1,
      name: 'facebook',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 14,
      rent: {
        baseRent: calcBought(prAr[11]),
        bigStar: calcRent(prAr[11], 5),
        fourStar: calcRent(prAr[11], 4),
        freeStar: calcRent(prAr[11], 3),
        oneStar: calcRent(prAr[11], 1),
        twoStar: calcRent(prAr[11], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[11]),
        buyoutPrice: calcBuyout(prAr[11]),
        pledgePrice: calcPledge(prAr[11]),
        startPrice: prAr[11],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/3_web/twitter.svg',
      fieldGroup: 3,
      fieldLine: 1,
      name: 'twitter',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 15,
      rent: {
        baseRent: calcBought(prAr[12]),
        bigStar: calcRent(prAr[12], 5),
        fourStar: calcRent(prAr[12], 4),
        freeStar: calcRent(prAr[12], 3),
        oneStar: calcRent(prAr[12], 1),
        twoStar: calcRent(prAr[12], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[12]),
        buyoutPrice: calcBuyout(prAr[12]),
        pledgePrice: calcPledge(prAr[12]),
        startPrice: prAr[12],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/audi.svg',
      fieldGroup: 0,
      fieldLine: 1,
      name: 'audi',
      level: 0,
      type: FieldType.AUTO,
    },
    {
      fieldPosition: 16,
      rent: {
        baseRent: calcBought(prAr[13]),
        bigStar: calcRent(prAr[13], 5),
        fourStar: calcRent(prAr[13], 4),
        freeStar: calcRent(prAr[13], 3),
        oneStar: calcRent(prAr[13], 1),
        twoStar: calcRent(prAr[13], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[13]),
        buyoutPrice: calcBuyout(prAr[13]),
        pledgePrice: calcPledge(prAr[13]),
        startPrice: prAr[13],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/4_drinks/coca_cola.svg',
      fieldGroup: 4,
      fieldLine: 1,
      name: 'coca_cola',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 17,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance.png',
      fieldLine: 1,
      name: 'chance',
      mnplSpecial: 1,
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 18,
      rent: {
        baseRent: calcBought(prAr[14]),
        bigStar: calcRent(prAr[14], 5),
        fourStar: calcRent(prAr[14], 4),
        freeStar: calcRent(prAr[14], 3),
        oneStar: calcRent(prAr[14], 1),
        twoStar: calcRent(prAr[14], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[14]),
        buyoutPrice: calcBuyout(prAr[14]),
        pledgePrice: calcPledge(prAr[14]),
        startPrice: prAr[14],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/4_drinks/pepsi.svg',
      fieldGroup: 4,
      fieldLine: 1,
      name: 'pepsi',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 19,
      rent: {
        baseRent: calcBought(prAr[15]),
        bigStar: calcRent(prAr[15], 5),
        fourStar: calcRent(prAr[15], 4),
        freeStar: calcRent(prAr[15], 3),
        oneStar: calcRent(prAr[15], 1),
        twoStar: calcRent(prAr[15], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[15]),
        buyoutPrice: calcBuyout(prAr[15]),
        pledgePrice: calcPledge(prAr[15]),
        startPrice: prAr[15],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/4_drinks/fanta.svg',
      fieldGroup: 4,
      fieldLine: 1,
      name: 'fanta',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 20,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/jackpot.svg',
      fieldCorner: 2,
      mnplSpecial: 1,
      name: 'casino',
      level: 0,
      type: FieldType.CASINO,
    },
    {
      fieldPosition: 21,
      rent: {
        baseRent: calcBought(prAr[16]),
        bigStar: calcRent(prAr[16], 5),
        fourStar: calcRent(prAr[16], 4),
        freeStar: calcRent(prAr[16], 3),
        oneStar: calcRent(prAr[16], 1),
        twoStar: calcRent(prAr[16], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[16]),
        buyoutPrice: calcBuyout(prAr[16]),
        pledgePrice: calcPledge(prAr[16]),
        startPrice: prAr[16],
      },
      imgSrc:
        'https://m1.dogecdn.wtf/fields/brands/5_airlines/american_airlines.svg',
      fieldLine: 2,
      fieldGroup: 5,
      name: 'american_airlines',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 22,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance.png',
      mnplSpecial: 1,
      fieldLine: 2,
      name: 'chance',
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 23,
      rent: {
        baseRent: calcBought(prAr[17]),
        bigStar: calcRent(prAr[17], 5),
        fourStar: calcRent(prAr[17], 4),
        freeStar: calcRent(prAr[17], 3),
        oneStar: calcRent(prAr[17], 1),
        twoStar: calcRent(prAr[17], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[17]),
        buyoutPrice: calcBuyout(prAr[17]),
        pledgePrice: calcPledge(prAr[17]),
        startPrice: prAr[17],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/5_airlines/lufthansa.svg',
      fieldGroup: 5,
      fieldLine: 2,
      name: 'lufthansa',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 24,
      rent: {
        baseRent: calcBought(prAr[18]),
        bigStar: calcRent(prAr[18], 5),
        fourStar: calcRent(prAr[18], 4),
        freeStar: calcRent(prAr[18], 3),
        oneStar: calcRent(prAr[18], 1),
        twoStar: calcRent(prAr[18], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[18]),
        buyoutPrice: calcBuyout(prAr[18]),
        pledgePrice: calcPledge(prAr[18]),
        startPrice: prAr[18],
      },
      imgSrc:
        'https://m1.dogecdn.wtf/fields/brands/5_airlines/british_airways.svg',
      fieldGroup: 5,
      fieldLine: 2,
      name: 'british_airways',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 25,
      rent: {
        baseRent: calcBought(prAr[19]),
        bigStar: calcRent(prAr[19], 5),
        fourStar: calcRent(prAr[19], 4),
        freeStar: calcRent(prAr[19], 3),
        oneStar: calcRent(prAr[19], 1),
        twoStar: calcRent(prAr[19], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[19]),
        buyoutPrice: calcBuyout(prAr[19]),
        pledgePrice: calcPledge(prAr[19]),
        startPrice: prAr[19],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/ford.svg',
      fieldGroup: 0,
      fieldLine: 2,
      name: 'ford',
      level: 0,
      type: FieldType.AUTO,
    },
    {
      fieldPosition: 26,
      rent: {
        baseRent: calcBought(prAr[20]),
        bigStar: calcRent(prAr[20], 5),
        fourStar: calcRent(prAr[20], 4),
        freeStar: calcRent(prAr[20], 3),
        oneStar: calcRent(prAr[20], 1),
        twoStar: calcRent(prAr[20], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[20]),
        buyoutPrice: calcBuyout(prAr[20]),
        pledgePrice: calcPledge(prAr[20]),
        startPrice: prAr[20],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/6_food/mcdonalds.svg',
      fieldGroup: 6,
      fieldLine: 2,
      name: 'mcdonalds',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 27,
      rent: {
        baseRent: calcBought(prAr[21]),
        bigStar: calcRent(prAr[21], 5),
        fourStar: calcRent(prAr[21], 4),
        freeStar: calcRent(prAr[21], 3),
        oneStar: calcRent(prAr[21], 1),
        twoStar: calcRent(prAr[21], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[21]),
        buyoutPrice: calcBuyout(prAr[21]),
        pledgePrice: calcPledge(prAr[21]),
        startPrice: prAr[21],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/6_food/burger_king.svg',
      fieldGroup: 6,
      fieldLine: 2,
      name: 'burger_king',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 28,
      rent: {
        baseRent: calcBought(prAr[22]),
        bigStar: calcRent(prAr[22], 5),
        fourStar: calcRent(prAr[22], 4),
        freeStar: calcRent(prAr[22], 3),
        oneStar: calcRent(prAr[22], 1),
        twoStar: calcRent(prAr[22], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[22]),
        buyoutPrice: calcBuyout(prAr[22]),
        pledgePrice: calcPledge(prAr[22]),
        startPrice: prAr[22],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/9_games/rovio.svg',
      fieldGroup: 9,
      fieldLine: 2,
      name: 'rovio',
      level: 0,
      type: FieldType.IT,
      currency: CurrencyType.MULTIPLIER,
    },
    {
      fieldPosition: 29,
      rent: {
        baseRent: calcBought(prAr[23]),
        bigStar: calcRent(prAr[23], 5),
        fourStar: calcRent(prAr[23], 4),
        freeStar: calcRent(prAr[23], 3),
        oneStar: calcRent(prAr[23], 1),
        twoStar: calcRent(prAr[23], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[23]),
        buyoutPrice: calcBuyout(prAr[23]),
        pledgePrice: calcPledge(prAr[23]),
        startPrice: prAr[23],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/6_food/kfc.svg',
      fieldGroup: 6,
      fieldLine: 2,
      name: 'kfc',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 30,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/goToJail.png',
      mnplSpecial: 1,
      fieldCorner: 3,
      name: 'arest',
      level: 0,
      type: FieldType.JAIL,
    },
    {
      fieldPosition: 31,
      rent: {
        baseRent: calcBought(prAr[24]),
        bigStar: calcRent(prAr[24], 5),
        fourStar: calcRent(prAr[24], 4),
        freeStar: calcRent(prAr[24], 3),
        oneStar: calcRent(prAr[24], 1),
        twoStar: calcRent(prAr[24], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[24]),
        buyoutPrice: calcBuyout(prAr[24]),
        pledgePrice: calcPledge(prAr[24]),
        startPrice: prAr[24],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/7_hotels/holiday_inn.svg',
      fieldGroup: 7,
      fieldLine: 3,
      name: 'holiday_inn',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 32,
      rent: {
        baseRent: calcBought(prAr[25]),
        bigStar: calcRent(prAr[25], 5),
        fourStar: calcRent(prAr[25], 4),
        freeStar: calcRent(prAr[25], 3),
        oneStar: calcRent(prAr[25], 1),
        twoStar: calcRent(prAr[25], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[25]),
        buyoutPrice: calcBuyout(prAr[25]),
        pledgePrice: calcPledge(prAr[25]),
        startPrice: prAr[25],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/7_hotels/radisson_blu.svg',
      fieldGroup: 7,
      fieldLine: 3,
      name: 'radisson_blu',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 33,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance_rotated.png',
      mnplSpecial: 1,
      fieldLine: 3,
      name: 'chance_rotated',
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 34,
      rent: {
        baseRent: calcBought(prAr[26]),
        bigStar: calcRent(prAr[26], 5),
        fourStar: calcRent(prAr[26], 4),
        freeStar: calcRent(prAr[26], 3),
        oneStar: calcRent(prAr[26], 1),
        twoStar: calcRent(prAr[26], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[26]),
        buyoutPrice: calcBuyout(prAr[26]),
        pledgePrice: calcPledge(prAr[26]),
        startPrice: prAr[26],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/7_hotels/novotel.svg',
      fieldGroup: 7,
      fieldLine: 3,
      name: 'novotel',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 35,
      rent: {
        baseRent: calcBought(prAr[27]),
        bigStar: calcRent(prAr[27], 5),
        fourStar: calcRent(prAr[27], 4),
        freeStar: calcRent(prAr[27], 3),
        oneStar: calcRent(prAr[27], 1),
        twoStar: calcRent(prAr[27], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[27]),
        buyoutPrice: calcBuyout(prAr[27]),
        pledgePrice: calcPledge(prAr[27]),
        startPrice: prAr[27],
      },
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/0_auto/land_rover.svg',
      fieldGroup: 0,
      fieldLine: 3,
      name: 'land_rover',
      level: 0,
      type: FieldType.AUTO,
    },
    {
      fieldPosition: 36,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/tax_luxury.png',
      mnplSpecial: 1,
      fieldLine: 3,
      name: 'tax_luxury',
      level: 0,
      rent: {
        baseRent: calcBought(prAr[28]),
        bigStar: calcRent(prAr[28], 5),
        fourStar: calcRent(prAr[28], 4),
        freeStar: calcRent(prAr[28], 3),
        oneStar: calcRent(prAr[28], 1),
        twoStar: calcRent(prAr[28], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[28]),
        buyoutPrice: calcBuyout(prAr[28]),
        pledgePrice: calcPledge(prAr[28]),
        startPrice: prAr[28],
      },
      type: FieldType.TAX,
    },
    {
      fieldPosition: 37,
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/8_smartphones/apple.svg',
      fieldLine: 3,
      fieldGroup: 8,
      rent: {
        baseRent: calcBought(prAr[29]),
        bigStar: calcRent(prAr[29], 5),
        fourStar: calcRent(prAr[29], 4),
        freeStar: calcRent(prAr[29], 3),
        oneStar: calcRent(prAr[29], 1),
        twoStar: calcRent(prAr[29], 2),
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: calcBranch(prAr[29]),
        buyoutPrice: calcBuyout(prAr[29]),
        pledgePrice: calcPledge(prAr[29]),
        startPrice: prAr[29],
      },
      name: 'apple',
      level: 0,
      type: FieldType.COMPANY,
    },
    {
      fieldPosition: 38,
      imgSrc: 'https://m1.dogecdn.wtf/fields/special/chance_rotated.png',
      mnplSpecial: 1,
      fieldLine: 3,
      name: 'chance_rotated',
      level: 0,
      type: FieldType.CHANCE,
    },
    {
      fieldPosition: 39,
      imgSrc: 'https://m1.dogecdn.wtf/fields/brands/8_smartphones/nokia.svg',
      fieldLine: 3,
      fieldGroup: 8,
      rent: {
        baseRent: 1000,
        bigStar: 20000,
        fourStar: 17000,
        freeStar: 14000,
        oneStar: 2000,
        twoStar: 6000,
        paymentMultiplier: 0,
      },
      price: {
        branchPrice: 2000,
        buyoutPrice: 2400,
        pledgePrice: 2000,
        startPrice: 4000,
      },
      name: 'nokia',
      level: 0,
      type: FieldType.COMPANY,
    },
  ];
};

export const users: UsersEntity[] = [
  {
    name: 'Konstantin',
    registrationType: 'vk',
    vip: true,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Diman',
    registrationType: 'vk',
    vip: false,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Feodr',
    registrationType: 'vk',
    vip: false,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Ivan',
    registrationType: 'vk',
    vip: false,
    avatar: '/avatars/konstanstin.png',
  },
  {
    name: 'Maxim',
    registrationType: 'vk',
    vip: true,
    avatar: '/avatars/konstanstin.png',
  },
];

console.log(1231231231, fieldsForSave());
