export const BOARD_PARAMS = {
  LINE_TRANSITION_TIMEOUT: 700,
  JAIL_TURNS: 3,
  JAIL_POSITION: 10,
  UN_JAIL_PRICE: 500,

  ONE_FIELD_PERCENT: 8,
  TWO_FIELD_PERCENT: 12,
  FREE_FIELD_PERCENT: 20,

  ONE_AUTO_PERCENT: 12.5,
  TWO_AUTO_PERCENT: 25,
  FREE_AUTO_PERCENT: 50,
  FOUR_AUTO_PERCENT: 100,

  ONE_IT_FIELD_MULT: 7,
  TWO_IT_FIELD_MULT: 16,

  START_BONUS: 3000,
  START_PASSING_BONUS: 2000,

  BANK_PLAYER_ID: 0,
  MORTGAGE_TURNS: 15,
};
